- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: augenrules load
  command: augenrules --load
  notify:
  - restart auditd

- name: update grub
  command: update-grub 

- name: update trusted ca debian
  command: update-ca-certificates
