---
- name: Enforce soft and hard limit for open files in system
  lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: '*  - nofile  32768'

- name: Enforce session required
  lineinfile:
    path: /etc/pam.d/common-session
    state: present
    line: session required pam_limits.so
  when: ansible_os_family == "Debian"

- name: Inject Azure DSR script
  copy:
    src: files/usr/local/sbin/provision-kubernetes-dsr
    dest: /usr/local/sbin/provision-kubernetes-dsr
    mode: 0755
  when: ansible_os_family == "Debian"
