- name: "disabled apparmor profile: delete"
  file: 
    path: "{{ item }}"
    state: absent
  with_items: "{{ diabled_apparmor_profile }}"

- name: "disabled apparmor profile: azure"
  file:
    path: "/etc/apparmor.d/sbin.dhclient"
    state: absent
  when:
    packer_builder_type.startswith('azure')
