- name: "login.defs"
  lineinfile:
    dest: /etc/login.defs
    regexp: "^{{ item.parameter }}"
    line: "{{ item.parameter }} {{ item.value }}"
    state: present
  with_items: 
  - parameter: ENCRYPT_METHOD
    value: "SHA512"
  - parameter: PASS_MIN_DAYS
    value: "1"
  - parameter: PASS_MAX_DAYS
    value: "60"
  - parameter: UMASK
    value: "077"
  - parameter: CREATE_HOME
    value: "yes"

- name: "login.defs: set inactive password lock"
  command: useradd -D -f 30

- name: "login.defs: set autologout timeout"
  blockinfile:
    dest: /etc/profile.d/autologout.sh
    state: present
    create: yes
    insertbefore: EOF
    marker: "# {mark} MCI hardening"
    block: |
      TMOUT=900
      readonly TMOUT
      export TMOUT

- name: "login.defs: ensure group sugroup exists"
  group:
    name: sugroup
    state: present

- name: "login.defs: set sugroup in /etc/pam.d/su"
  lineinfile:
    dest: /etc/pam.d/su
    line: auth required pam_wheel.so use_uid group=sugroup
    state: present