- name: "profile d: TMOUT"
  blockinfile:
    dest: /etc/profile.d/autologout.sh
    state: present
    create: yes
    insertbefore: EOF
    marker: "# {mark} MCI hardening"
    block: |
      TMOUT=900
      readonly TMOUT
      export TMOUT